#pragma once

#define ANSI_ESCAPE "\x1b"

#define ANSI_RESET ANSI_ESCAPE "[0m"

#define ANSI_FGCOLOR_BLACK ANSI_ESCAPE "[30m"
#define ANSI_FGCOLOR_RED ANSI_ESCAPE "[31m"
#define ANSI_FGCOLOR_GREEN ANSI_ESCAPE "[32m"
#define ANSI_FGCOLOR_YELLOW ANSI_ESCAPE "[33m"
#define ANSI_FGCOLOR_BLUE ANSI_ESCAPE "[34m"
#define ANSI_FGCOLOR_MAGENTA ANSI_ESCAPE "[35m"
#define ANSI_FGCOLOR_CYAN ANSI_ESCAPE "[36m"
#define ANSI_FGCOLOR_WHITE ANSI_ESCAPE "[37m"

#define ANSI_FGCOLOR_BRIGHT_BLACK ANSI_ESCAPE "[1;30m"
#define ANSI_FGCOLOR_BRIGHT_RED ANSI_ESCAPE "[1;31m"
#define ANSI_FGCOLOR_BRIGHT_GREEN ANSI_ESCAPE "[1;32m"
#define ANSI_FGCOLOR_BRIGHT_YELLOW ANSI_ESCAPE "[1;33m"
#define ANSI_FGCOLOR_BRIGHT_BLUE ANSI_ESCAPE "[1;34m"
#define ANSI_FGCOLOR_BRIGHT_MAGENTA ANSI_ESCAPE "[1;35m"
#define ANSI_FGCOLOR_BRIGHT_CYAN ANSI_ESCAPE "[1;36m"
#define ANSI_FGCOLOR_BRIGHT_WHITE ANSI_ESCAPE "[1;37m"

#define ANSI_FGCOLOR_24B(r, g, b) ANSI_ESCAPE "[38;2;" #r ";" #g ";" #b "m"
