name: Nightly release

# Run on every push to main (aka "rolling releases")
#on:
#  push:
#    branches: [main]
#    paths-ignore:
#    - docs/**
#    - '**.md'

# Run once per day (aka "nightly releases")
on:
  schedule:
    - cron: '45 3 * * *'
  workflow_dispatch: # Enable manual runs

env:
  NIGHTLY_TAG_NAME: latest-nightly

concurrency:
  group: ymir-nightly-releases
  cancel-in-progress: true

jobs:
  check_date:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v4
      - name: print latest_commit
        run: echo ${{ github.sha }}
  
      - id: should_run
        continue-on-error: true
        name: check latest commit is less than a day
        if: ${{ github.event_name == 'schedule' }}
        run: test -z $(git rev-list  --after="24 hours"  ${{ github.sha }}) && echo "should_run=false" >> $GITHUB_OUTPUT

  commit-sha:
    runs-on: ubuntu-latest
    needs: [check_date]
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    outputs:
      build-version: ${{ steps.get-sha.outputs.short-sha }}
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .
      - name: Get short commit SHA
        id: get-sha
        run: echo "short-sha=$(git rev-parse --short=8 HEAD)" >> "$GITHUB_OUTPUT"

  build-all:
    uses: StrikerX3/Ymir/.github/workflows/build.yaml@ci-test-stub
    needs: [commit-sha]
    with:
      dev-build: true
      build-version: ${{ needs.commit-sha.outputs.build-version }}

  release:
    runs-on: ubuntu-latest
    needs: [build-all]

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Create/update ${{ env.NIGHTLY_TAG_NAME }} tag
        run: |
          git tag -f ${{ env.NIGHTLY_TAG_NAME }}
          git push origin -f --tags

      - name: Download Ymir artifacts
        uses: actions/download-artifact@v4
        with:
          path: ymir
          pattern: ymir-*
          merge-multiple: true

      - name: Delete existing release
        uses: author/action-rollback@stable
        with:
          tag: ${{ env.NIGHTLY_TAG_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true  # in case this fails if the release doesn't exist

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: Latest nightly release
          draft: false
          prerelease: true
          generate_release_notes: false
          make_latest: false
          tag_name: ${{ env.NIGHTLY_TAG_NAME }}
          body: |
            This is a nightly release built from the latest commit. Before you use these builds, **make sure to backup your data, especially the save states!**
          
            Save states are constantly evolving and are only guaranteed to be compatible on stable (numbered) releases.
            The file format may be changed without notice, so be careful when using save states from nightly releases.

            You can find the changelog for this build [here](https://github.com/StrikerX3/Ymir/blob/latest-nightly/CHANGELOG.md).
          files: |
            ymir/*
          
